services: 
    rh_user.my_provider: 
        class: Rh\UserBundle\Security\Provider\MyProvider
        public: false
        arguments: ["@fos_user.user_manager"]
        
    rh_user.registration.form.type: 
        class: Rh\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags: 
            - { name: form.type, alias: rh_user_registration }
            
    rh_user.search.service:
        class: Rh\UserBundle\Service\Search\Basic
        arguments: [ @doctrine.orm.entity_manager ]