<?php

namespace Rh\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeriePontRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeriePontRepository extends EntityRepository
{
}