<?php

namespace Rh\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContratTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratTypeRepository extends EntityRepository {
}
