<?php

namespace Rh\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PrimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrimeRepository extends EntityRepository {
}
