<?php

namespace Rh\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfilHeureMaxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilHeureMaxRepository extends EntityRepository
{
}