<?php

namespace Rh\PointageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * typeRemboursementReelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeRemboursementReelRepository extends EntityRepository
{
}