RhCongesBundle:
    resource: "@RhCongesBundle/Resources/config/routing.yml"
    prefix:   /

RhPointageBundle:
    resource: "@RhPointageBundle/Resources/config/routing.yml"
    prefix:   /

RhAdminBundle:
    resource: "@RhAdminBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
