parameters:
#    rh_conges.example.class: Rh\CongesBundle\Example

services:
#    rh_conges.example:
#        class: %rh_conges.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
